# Backend jobs
# Build, test and publish Docker images for a site
hub:
  parameters:
    site:
      type: string
  docker:
    - image: circleci/buildpack-deps:stretch
      environment:
        RICHIE_SITE: << parameters.site >>
  working_directory: ~/fun
  steps:
    - checkout
    # Generate a version.json file describing app release
    - generate-version-file:
        site: << parameters.site >>
    # Activate docker-in-docker (with layers caching enabled)
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Build docker images
        command: make env.d/aws && make build
    - run:
        name: Check built image availability
        command: |
            docker images "<< parameters.site >>:development"
            docker images "<< parameters.site >>:production"
            docker images "<< parameters.site >>-nginx:production"
    - run:
        name: Check version.json file
        command: make ci-version
    - run:
        name: Run Django migrations
        command: make ci-migrate
    - run:
        name: Run Django checks with production image
        command: make ci-check
    # Publish images to DockerHub only for tags and the master branch:
    #   - for a v1.0.1 tag, publish Docker tags "1.0.1"  and "latest"
    #   - for the master branch, publish a "master" tag
    #
    # Nota bene: logged user (see "Login to DockerHub" step) must have write
    # permission for the project's repository; this also implies that the
    # DockerHub repository already exists.
    - when:
        condition:
            or:
              - << pipeline.git.tag >>
              - equal:
                - << pipeline.git.branch >>
                - master
        steps:
          - run:
              name: For a release, check that the tag and versions are in sync
              command: |
                if [[ -n "$CIRCLE_TAG" ]]; then
                    bin/ci check_tag << parameters.site >> "$CIRCLE_TAG"
                fi
          # Login to DockerHub to Publish new images
          #
          # Nota bene: you'll need to define the following secrets environment vars
          # in CircleCI interface:
          #
          #   - DOCKER_USER
          #   - DOCKER_PASS
          - run:
              name: Login to DockerHub
              command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          # Set environment variables that will be used in next steps
          - run:
              name: Compute Docker tag
              command: |
                DOCKER_TAG=$([[ -z "$CIRCLE_TAG" ]] && echo $CIRCLE_BRANCH || echo ${CIRCLE_TAG} | sed 's/^<< parameters.site >>-//')
                echo "export DOCKER_TAG=${DOCKER_TAG}" >> $BASH_ENV
          # Tag images
          - run:
              name: Tag app image
              command: |
                docker images fundocker/<< parameters.site >>
                # Display either:
                # - DOCKER_TAG: master (Git branch)
                # or
                # - DOCKER_TAG: 1.1.2 (Git tag v1.1.2)
                echo "DOCKER_TAG: ${DOCKER_TAG}"
                docker tag << parameters.site >>:production fundocker/<< parameters.site >>:${DOCKER_TAG}
                if [[ -n "$CIRCLE_TAG" ]]; then
                    docker tag << parameters.site >>:production fundocker/<< parameters.site >>:latest
                fi
                docker images | grep -E "^fundocker/<< parameters.site >>\s*(${DOCKER_TAG}.*|latest|master)"
          - run:
              name: Tag nginx image
              command: |
                docker images fundocker/<< parameters.site >>-nginx
                echo "DOCKER_TAG: ${DOCKER_TAG}"
                docker tag << parameters.site >>-nginx:production fundocker/<< parameters.site >>-nginx:${DOCKER_TAG}
                if [[ -n "$CIRCLE_TAG" ]]; then
                    docker tag << parameters.site >>-nginx:production fundocker/<< parameters.site >>-nginx:latest
                fi
                docker images | grep -E "^fundocker/<< parameters.site >>-nginx\s*(${DOCKER_TAG}.*|latest|master)"
          # Publish images
          - run:
              name: Publish app image
              command: |
                docker push fundocker/<< parameters.site >>:${DOCKER_TAG}
                if [[ -n "$CIRCLE_TAG" ]]; then
                  docker push fundocker/<< parameters.site >>:latest
                fi
          - run:
              name: Publish nginx image
              command: |
                docker push fundocker/<< parameters.site >>-nginx:${DOCKER_TAG}
                if [[ -n "$CIRCLE_TAG" ]]; then
                  docker push fundocker/<< parameters.site >>-nginx:latest
                fi
